sudo: required
dist: trusty
language: c
compiler:
- gcc
addons:
  apt:
    packages:
    - autoconf
    - libtool
    - libssl-dev
    - libsodium-dev
    - libev-dev
    - gawk
    - debhelper
    - dh-systemd
    - init-system-helpers
    - pkg-config
    - asciidoc
    - xmlto
    - libnetfilter-conntrack-dev
script:
- dpkg-buildpackage -b -us -uc -i
deploy:
  provider: releases
  api_key:
    secure: Lu6FkG0o02sS1ZbO6CZ9SV4fXs7f+TMebh6KtxxdKyN0cukdbed7C4L+hGzMygs9RQ3JqL6J4Ja2RbPMAOAhiQKbcFmi2e9G00Cza5o+jFX3tMqzn4s/zL0rh8lsmdHpEx2xNAnLkFyW6Ow5wzqtirG2QtT6oN83y/LfP1WgRt5wA3nWBREOT4KuGyiT5FhDYAhxptNyrKQFwqdtgIL6FOC3WxnwK4QEtgP5BOgyd91TLVstX02gO5D7zVeZweJZ+OkboLN4OfWd6j/Z4HUc9DUbWXxbzg7S45pSeTgFQzd/Mgn4i/u+hs3DO9GuPgjBXuGAr3VKqMcCvdcofm0lrDsfHxh5nkzhrHWPpiirjD3cyH3jIMMI6moeSRZJJbapJ4IO9XNcJ44QRkkarFNE/6a4ObSyj4aaJftXTqz3Kl20c243svzDaUv4Htg2oILKdL6ftOg/eSED35/LgTSsy5YdxH5arQf9MRU9mlJlLvciYSuRcDOQMtvEn1iuexz+G+QwxMPgNF9ZDM5u2wlgnNJz4HboBthM2A1nK7Qk2LAC4FUU9FPDYKOd0WOGJFC5VdG0QDokkSxOTAtSUhEFNSkaAmoWtGvZzkOOVjMaBr907eclRRNJytDqKwx1nd/Y2EXL4GyaB2QIchdugnptBvcvw/zDJUC7KPAvrT4QTwE=
  file: "../*.deb"
  skip_cleanup: true
  file_glob: true
  on:
    all_branches: true
    tags: true
